config/routes.rb
Rails.application.routes.draw do
  get 'registration/index'
  resources :ads
  devise_for :admins
  resources :categories
  get 'home/index'
  get 'home/about'
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
 belongs_to :admin
 belongs_to :category
 has_one_attached :image;
end

app/models/admin.rb
class Admin < ApplicationRecord
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable      
    has_many :ads
   has_one_attached :avatar
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]
  def index
    @ads = current_admin.ad
  end
 
  def show
    @ad = Ad.find(params[:id])
  end

  def new 
    @ad = Ad.new
  end

  def edit
  end

  def create
    @ad = Ad.new(ad_params)
    @ad.admin_id = current_admin.id 
    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_ad
    @ad = Ad.find(params[:id])
  end

  def ad_params
        params.require(:ad).permit(:title, :description, :price, :location, :mobileNumber, :admin_id, :category_id, :image)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
    @categories =Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end
  private  
    def category_params
      params.require(:category).permit(:title,  :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(ad.errors.count, "error") %>
        prohibited this ad from being saved:
      </h2>
      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title , class:"form-control", placeholder:"Enter Ads Title"%>
  </div>
  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description , class:"form-control", placeholder:"Enter some description"%>
  </div>
  <div class="field form-group">
    <%= form.label :price %>
    <%= form.text_field :price , class:"form-control", placeholder:"Enter price of the product"%>
  </div>
  <div class="field form-group">
    <%= form.label :location %>
    <%= form.text_field :location , class:"form-control", placeholder:"Enter the address of company"%>
  </div>
  <div class="field form-group">
    <%= form.label :mobileNumber %>
    <%= form.text_field :mobileNumber , class:"form-control", placeholder:"Enter contact number"%>
  </div>
  <div class="field form-group">
    <%= form.label :category %>
    <%= form.select :category_id, Category.all.collect { |p| [ p.title, p.id] }, include_blank: true  %> 
  </div>
  <div class="form-group">
    <% if @ad.image.attached? %>
      <%= image_tag @ad.image%>
    <% end%>
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <br>
  <div class="actions ">
  <%= form.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>
<%= render 'form', ad: @ad %>
<br>
<%= link_to 'Show', @ad, class:"btn btn-info" %>
<%= link_to 'Back', ads_path, class:" btn btn-danger"  %>

app/views/ads/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<strong>
  <h2>
    Ads
  </h2>
</strong>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th>Mobilenumber</th>
      <th>category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @ads.each do |ad| %>
      <tr class="table-light">
        <td>   
          <%= image_tag ad.image, height:50, width:50 %>
        </td>
        <td>
          <%= ad.title %>
        </td>
        <td>
          <%= ad.description %>
        </td>
        <td>
          <%= ad.price %>
        </td>
        <td>
          <%= ad.location %>
        </td>
        <td>
          <%= ad.mobileNumber %>
        </td>
        <td>
          <%= ad.category_id %>
        </td>
        <td>  
          <%= link_to 'Show', ad, class:" btn btn-warning" %>
        </td>
        <td>
          <%= link_to 'Edit', edit_ad_path(ad), class:" btn btn-success" %>
        </td>
        <td>
          <%= link_to 'Destroy', ad, class:" btn btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Ad', new_ad_path,class:"btn btn-primary"  %>

app/views/ads/new.html.erb
<h1>New Ad</h1>
<%= render 'form', ad: @ad %>
<div class="btn btn-primary mp-5" >
    back<%= link_to 'Back', ads_path %>
</div>

app/views/ads/show.html.erb
<p id="notice"><%= notice %>
</p>
<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @ad.price %>
</p>
<p>
  <strong>Location:</strong>
  <%= @ad.location %>
</p>
<p>
  <strong>Mobilenumber:</strong>
  <%= @ad.mobileNumber %>
</p>
<p>
  <strong>Category:</strong>
  <%= @ad.category.title %> 
</p>
<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form|%>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%=pluralize(category.errors.count, "error")%>
        prohibited this category from being saved:
      </h2>
      <ul>
        <% category.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title , class:"form-control", placeholder:"Enter category Title"%>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:" Enter the description" %>
  </div>
  <br>
  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= link_to 'Show', @category, class:"btn btn-info"%>
<%= link_to 'Back', categories_path, class:"btn btn-danger" %>
<br>
<h4>
    <strong>
        Editing Category
    </strong>
</h4>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<h3>
  <strong>
    Categories
  </strong>
</h3>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Title</th>  
      <th>Description</th>
      <th colspan="3"></th>
    </tr> 
  </thead>
  <tbody> 
    <% @categories.each do |category| %>
      <tr class="table-light">
        <td>
          <%= category.title %>
        </td>
        <td>
          <%= category.description%>
        </td>
        <td>
          <a> 
            <%= link_to 'Show', category,class:"btn btn-warning" %>
          </a>
        </td>
        <td>
          <a>
            <%= link_to 'Edit', edit_category_path(category),class:"btn btn-success" %>
          </a>
        </td>
        <td>
          <a>
            <%= link_to 'Destroy', category, class:"btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<a> <%= link_to 'New Category', new_category_path, class:"btn btn-primary" %></a>
</button>

app/views/categories/new.html.erb
<%= link_to 'Back', categories_path, class:"btn btn-info", style:"margin-left:1000px;" %>
<br>
<h4>
    <strong>
        Add New Category
    </strong>
</h4>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <h3 id="notice">
    <%= notice %>
  </h3>
  <h4 class="display-4"><strong>Title:</strong>
    <%= @category.title %>
  </h4>
  <p class="lead">  <strong>Description:</strong>
    <%= @category.description %>
  </p>
  <hr class="my-4">
</div>
<%= link_to 'Edit', edit_category_path(@category), class:"btn btn-primary" %> 
<%= link_to 'Back', categories_path, class:"btn btn-danger"  %>

app/views/home/_footer.html.erb
<div class="container-flex">
    <hr class="my-2">
    <strong>
        <p>
            Copyright are reserved to CLUSTOX
        </p>
    </strong>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <strong>
        <%= link_to "OLX", root_path, class:"navbar-brand ms-2"%>
    </strong>
    <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="search location" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">
            Search
        </button>
    </form>
    <form class="d-flex ">
        <input class="form-control ms-5 me-2" type="search" placeholder="search product" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">
            Search
        </button>
    </form>
    <nav class="navbar ms-auto">
        <% if admin_signed_in?%>
        <div class="nav-item dropdown">
            <button class="btn btn-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Login
            </button>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark" aria-labelledby="navbarDropdown">
                <li>
                    <a>
                     <%= link_to "Category", categories_path,class:"btn btn-light w-100" %>
                    </a>
                </li>
                <li class="nav-item">
                    <a>
                        <%= link_to "My Ads", ads_path,class:"btn btn-dark w-100" %>
                    </a>
                </li>
                <li class="nav-item">
                    <a>
                        <%= link_to "Edit Profile", edit_admin_registration_path, class:"btn btn-dark w-100"%>
                    </a>
                </li>
                <li>
                    <a>
                        <%= link_to "Sign Out", destroy_admin_session_path, method: :delete,class:"btn btn-dark w-100" %>
                    </a>
                </li>
            </ul>
        </div>
        <% end%>
        <div class="collapse navbar-collapse  " id="navbarSupportedContent">
            <ul class="navbar-nav">
                <% if !admin_signed_in?%>
                <strong>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_admin_registration_path, class:"nav-link"%>
                    </li>
                </strong>
                <strong>
                    <li class="nav-item">
                        <%= link_to "Sign in", new_admin_session_path, class:"nav-link"%>
                    </li>
                </strong>
                <%end%>
            </ul>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</nav>

app/views/home/index.html.erb
<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Olx</title>
</head>
<body>
    <%= render 'home/header'%>
    <div class=" container mt-5 min-vh-100">
        <%= yield %>
    </div>
    <div class="text-center p-3 fixed-bottom ">
        <%= render 'home/footer'%>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>

</html>